version: '3'

#
# Resources :
# - gitlab, kubernetes & minikube : https://blog.ramjee.uk/minikube-and-gitlab-ci/
# - gitlab, docker, traefik, https : https://pg3.io/blog/gitlab-registry-docker-traefik/
#

services:

  gitlab:
    image: 'gitlab/gitlab-ce:14.1.7-ce.0'
    container_name: gitlab
    hostname: '${GITLAB_VIRTUAL_HOST}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${GITLAB_VIRTUAL_HOST}'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        nginx['listen_port'] = 80
        nginx['listen_https'] = false

        gitlab_rails['packages_enabled'] = true
        registry['enable'] = true
        registry_external_url 'https://${REGISTRY_VIRTUAL_HOST}'
        registry_nginx['listen_port'] = 80
        registry_nginx['listen_https'] = false

        gitlab_pages['enable'] = true
        pages_external_url "http://${GITLAB_PAGES_VIRTUAL_HOST}"
        gitlab_pages['listen_proxy'] = "0.0.0.0:5200"
        gitlab_pages['access_control'] = true
        gitlab_pages['gitlab_server'] = "http://${GITLAB_VIRTUAL_HOST}"
        pages_nginx['enable'] = false

        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.gmail.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "my-email"
        gitlab_rails['smtp_password'] = "my-gmail-password"
        gitlab_rails['smtp_domain'] = "smtp.gmail.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        gitlab_rails['gitlab_email_display_name'] = 'Email title'
        gitlab_rails['gitlab_email_from'] = 'my-email@gmail.com'
    expose:
      - 80
      - 5200
    ports:
      - '2222:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    network_mode: bridge
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab.rule=Host(`${GITLAB_VIRTUAL_HOST:-gitlab.localdomain}`)
      - traefik.http.routers.gitlab.entrypoints=websecure
      - traefik.http.routers.gitlab.service=gitlab
      - traefik.http.services.gitlab.loadbalancer.server.port=80
      - traefik.http.routers.registry.rule=Host(`${REGISTRY_VIRTUAL_HOST:-registry.localdomain}`)
      - traefik.http.routers.registry.entrypoints=websecure
      - traefik.http.routers.registry.service=registry
      - traefik.http.services.registry.loadbalancer.server.port=80
      - traefik.http.routers.gitlab-pages.rule=HostRegexp(`{subdomain:[a-z0-9]+}.${GITLAB_PAGES_VIRTUAL_HOST:-pages.localdomain}`)
      - traefik.http.routers.gitlab-pages.entrypoints=web
      - traefik.http.routers.gitlab-pages.service=gitlab-pages
      - traefik.http.services.gitlab-pages.loadbalancer.server.port=5200
      - traefik.http.routers.gitlab-pages.middlewares=gitlab-pages-auth
      - traefik.http.middlewares.gitlab-pages-auth.basicauth.users=${GITLAB_PAGES_BASIC_AUTH_HASHES}
