version: '3.4'

services:
  db:
    container_name: postgres-server
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USERNAME-root}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD-Secr3t!}
    ports:
      - "5432:5432"
    network_mode: bridge

  pg-admin:
    container_name: pgAdmin-server
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_ADMIN_USERNAME-root}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_ADMIN_PASSWORD-Secr3t!}
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    ports:
    - "5050:80"
    network_mode: bridge
    depends_on:
      - db
