version: '3'

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db
      - ./data/mongodb-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD:-Secr3t!}
    network_mode: bridge
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    expose:
      - 8081
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PASSWORD:-Secr3t!}
    network_mode: bridge
    restart: unless-stopped
    depends_on:
      - mongo
    labels:
      - traefik.enable=true
      - traefik.http.routers.mongo.rule=Host(`${MONGO_VIRTUAL_HOST:-mongo.docker.localhost}`)
      - traefik.http.routers.mongo.entrypoints=${MONGO_ENTRYPOINTS:-web}
