version: '3'

services:

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    healthcheck:
      test: redis-cli -p 6379 ping > /dev/null && echo OK
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./redis/data:/data
    network_mode: bridge
    restart: unless-stopped
